### PR TITLE
DNS: document iOS 14+ & macOS Big Sur encrypted DNS

### PR DESCRIPTION
**Pull request by Mikaela**
## Description

Resolves: #2059
Resolves: #2096

#### Check List 

- [x] I understand that by not opening an issue about a software/service/similar addition/removal, this pull request will be closed without merging.

- [x] I have read and understand [the contributing guidelines](https://github.com/privacytools/privacytools.io/blob/master/.github/CONTRIBUTING.md).

- [ ] The project is [Free Libre](https://en.wikipedia.org/wiki/Free_software) and/or [Open Source](https://en.wikipedia.org/wiki/Open-source_software) Software
  - I am not sure if *AdGuard* profiles cont as it's listed above on the page.
  - I don't know if *NextDNS* profile generator is open source.
  - *encrypted-dns.party* is open source.

* Netlify preview for the mainly edited page: https://deploy-preview-2099--privacytools-io.netlify.app/providers/dns/#appledns

* Code repository of the project (if applicable): https://gitlab.com/nitrohorse/ios14-encrypted-dns-mobileconfigs

### CODE REVIEW

**Comment by Mikaela** [comment]
I am opening this PR to show that I am working on this and to hopefully not duplicate work. I pushed this so heavy WIP as I want to work on this on another computer and the easiest way to do that with git is pushing it.

**Comment by Mikaela** [comment]
I think the only way to make this prettier would be delisting DNSCloak or demoting it as a third option after unsigned profiles. Thoughts?

**Comment by freddy-m** [comment]
I don't think that it  looks ugly as it is, certainly an improvement from when it was in card format.

**Review by freddy-m — APPROVED** [review]
LGTM

**Review by freddy-m — APPROVED** [review]
Looks even better to me (I hate reviewing things first).

**Pull request merged**
