### PR TITLE
Cleanup jQuery

### PR DESCRIPTION
**Pull request by Gusted**
## Description

As jQuery was only used for the tooltip implementation, it was better to have it rewritten in vanilla CSS and have another dependency removed. I've changed the `title` attributes to `data-original-title` so it was consistent with all other tooltips.
Bootstrap/Popper seems to work without jQuery and doesn't throw errors.

Resolves: #1356 

#### Check List 

- [x] I understand that by not opening an issue about a software/service/similar addition/removal, this pull request will be closed without merging.

- [x] I have read and understand [the contributing guidelines](https://github.com/privacytools/privacytools.io/blob/master/.github/CONTRIBUTING.md).

- [x] The project is [Free Libre](https://en.wikipedia.org/wiki/Free_software) and/or [Open Source](https://en.wikipedia.org/wiki/Open-source_software) Software

* Netlify preview for the mainly edited page: https://deploy-preview-2139--privacytools-io.netlify.app/

* Code repository of the project (if applicable):

### CODE REVIEW

**Comment by dngray** [comment]
I'll have a look at this one later today. Just need to verify everything works.

**Comment by Gusted** [comment]
Hey @dngray

Was their any update on this?

Regards,
Gusted

**Comment by dngray** [comment]
I've checked this out and it seems to work, so approving.

**Review by dngray — APPROVED** [review]

**Comment by Gusted** [comment]
> I've checked this out and it seems to work, so approving.

Thanks!

**Comment by dngray** [comment]
Hmm I think I've noticed a breakage. For example in https://github.com/privacytools/privacytools.io/commit/afd7e216ce9799a585f3dc8ff89aa243cd1d8e24 it looks like:



Where as after https://github.com/privacytools/privacytools.io/commit/21c894eef786e34b111918f83170a3783391687f



@Gusted not sure how I missed that the first time. Got any idea what is causing it?

**Comment by Gusted** [comment]
image
It seems to be happening on all warnings, I will have a look what's going on here.

**Comment by Gusted** [comment]
Aha, those little warnings has
```CSS
white-space: nowrap;
```
Which causes to let the tooltip inherit it and therefore make the tooltip content 1 long text.
I will open up a PR to fix this.

**Comment by dngray** [comment]
@Gusted much appreciated, this wasn't my area of expertise so it helps having someone who knows how to fix this nicely :+1:

**Comment by Gusted** [comment]
> @Gusted much appreciated, this wasn't my area of expertise so it helps having someone who knows how to fix this nicely +1

No problems.

**Pull request merged**
