### PR TITLE
Updated Bitwarden logo

### PR DESCRIPTION
**Pull request by jackmchou**
## Description

Resolves: #1960 

#### Check List 

- [x] I understand that by not opening an issue about a software/service/similar addition/removal, this pull request will be closed without merging.

- [x] I have read and understand [the contributing guidelines](https://github.com/privacytools/privacytools.io/blob/master/.github/CONTRIBUTING.md).

- [x] The project is [Free Libre](https://en.wikipedia.org/wiki/Free_software) and/or [Open Source](https://en.wikipedia.org/wiki/Open-source_software) Software

* Netlify preview for the mainly edited page: https://deploy-preview-1968--privacytools-io.netlify.app/software/passwords/ 

* Code repository of the project (if applicable): N/A

### CODE REVIEW

**Comment by dngray** [comment]
We like to optimize all SVGs we add to the site. This is a helpful guide as to how we do it with Inkscape:

optimize_svg

**Comment by jackmchou** [comment]
> 
> 
> We like to optimize all SVGs we add to the site. This is a helpful guide as to how we do it with Inkscape:
> 
> optimize_svg

Got it! Will do in the future. Could I also update the contributing guidelines with this information?

**Comment by nitrohorse** [comment]
@jackmchou that’s a good idea! Having the optimization recommendation somewhere visible will be helpful.

**Comment by dngray** [comment]
> Got it! Will do in the future. Could I also update the contributing guidelines with this information?

We should do that actually, and also mention that images must be 128x128 or 384x128

**Pull request merged**
