### PR TITLE
Add Kryptor as worth mentioning.

### PR DESCRIPTION
**Pull request by lynn-stephenson**
## Description

Resolves: #2064 
#### Check List

- [x] I understand that by not opening an issue about a software/service/similar addition/removal, this pull request will be closed without merging.

- [x] I have read and understand [the contributing guidelines](https://github.com/privacytools/privacytools.io/blob/master/.github/CONTRIBUTING.md).

- [x] The project is [Free Libre](https://en.wikipedia.org/wiki/Free_software) and/or [Open Source](https://en.wikipedia.org/wiki/Open-source_software) Software

* Netlify preview for the mainly edited page: https://deploy-preview-2100--privacytools-io.netlify.app/software/encryption-tools/

* Code repository of the project (if applicable): https://github.com/samuel-lucas6/Kryptor

### CODE REVIEW

**Review by freddy-m — APPROVED** [review]
LGTM, however this page is getting rather cluttered. Perhaps a future PR should be to clean this up!

**Comment by lynn-stephenson** [comment]
> LGTM, however this page is getting rather cluttered. Perhaps a future PR should be to clean this up!

Could you elaborate?

**Comment by samuel-lucas6** [comment]
@lynn-stephenson I hate to be a nuisance, but please could you add 'free and open source' to the Kryptor description. E.g. 'Kryptor - A free and open source file encryption program for Windows, macOS, and Linux.' I think the warning symbol might make some people think it's closed source since the other warnings are related to that. Many thanks.

**Comment by dngray** [comment]
> please could you add 'free and open source' to the Kryptor description

To be honest I'm more of a fan of doing https://github.com/privacytools/privacytools.io/pull/2108

**Pull request merged**
