### PR TITLE
Mention discontinuation uMatrix, mention uBlock advanced mode

### PR DESCRIPTION
**Pull request by dngray**
## Description

Resolves: https://github.com/privacytools/privacytools.io/issues/2057

#### Check List 

- [x] I understand that by not opening an issue about a software/service/similar addition/removal, this pull request will be closed without merging.

- [x] I have read and understand [the contributing guidelines](https://github.com/privacytools/privacytools.io/blob/master/.github/CONTRIBUTING.md).

- [x] The project is [Free Libre](https://en.wikipedia.org/wiki/Free_software) and/or [Open Source](https://en.wikipedia.org/wiki/Open-source_software) Software

* https://deploy-preview-2058--privacytools-io.netlify.app/browsers/#addons

### CODE REVIEW

**Review by Mikaela — APPROVED** [review]
LGTM, except that the descriptions are a bit of wall of text especially on mobile and I wonder if some line changes would make it more pleasant to look at.

**Review by freddy-m — APPROVED** [review]

**Comment by 3k2** [comment]
So what about noscript? far as I can tell it was removed due to fact that umatrix does the same thing now that umatrix isn't being maintained anymore is it good idea to add it back or not?

**Comment by dngray** [comment]
> So what about noscript? far as I can tell it was removed due to fact that umatrix does the same thing now that umatrix isn't being maintained anymore is it good idea to add it back or not?

uBlock advanced can do the same as NoScript, you can disable JavaScript and then enable it for various things.

See [Advanced mode](https://github.com/gorhill/uBlock/wiki/Advanced-user-features) with [dynamic filtering](https://github.com/gorhill/uBlock/wiki/Advanced-user-features). Take a look the differences between [easy mode](https://github.com/gorhill/uBlock/wiki/Blocking-mode:-easy-mode), [medium mode](https://github.com/gorhill/uBlock/wiki/Blocking-mode:-medium-mode), or [hard mode](https://github.com/gorhill/uBlock/wiki/Blocking-mode:-hard-mode).

**Comment by dngray** [comment]
One thing to add, uBlock currently works with Fenix (so if you use Firefox on Android), whereas uBlock does not.

**Comment by 3k2** [comment]
> > So what about noscript? far as I can tell it was removed due to fact that umatrix does the same thing now that umatrix isn't being maintained anymore is it good idea to add it back or not?
> 
> uBlock advanced can do the same as NoScript, you can disable JavaScript and then enable it for various things.
> 
> See [Advanced mode](https://github.com/gorhill/uBlock/wiki/Advanced-user-features) with [dynamic filtering](https://github.com/gorhill/uBlock/wiki/Advanced-user-features). Take a look the differences between [easy mode](https://github.com/gorhill/uBlock/wiki/Blocking-mode:-easy-mode), [medium mode](https://github.com/gorhill/uBlock/wiki/Blocking-mode:-medium-mode), or [hard mode](https://github.com/gorhill/uBlock/wiki/Blocking-mode:-hard-mode).

oh yes I forgot about that sorry! I feel kinda sad that umatrix isn't maintained anymore but I suppose it makes sense since ublock can do most of the things what umatrix did. So there's no point maintaining both which essentially do same.

**Comment by dngray** [comment]
> So there's no point maintaining both which essentially do same

That's pretty much what the author said (Raymond Hill) said:

https://github.com/uBlockOrigin/uMatrix-issues/issues/291#issuecomment-694988696

**Comment by unbranched** [comment]
In no way uBlock can replace uMatrix, or I'm missing some functionality:
-I set uBlock in advanced mode to block everything by default globally except images
-I visit a website that doesn't display correctly because of blocked css/third party images
-I allow the first party domain

Now the website works, but this implies enabled cosmetic elements and everything else, including scripts. What if I just want to display the website correctly while not running 1st party scripts? I can't.

I have no other choice than using ublock+noscript .

**Comment by justjosias** [comment]
There's nothing to worry about for now. It will be a while before uMatrix becomes outdated to the point it doesn't make sense to use it.

**Comment by lynn-stephenson** [comment]
We have no intention of recommending EOL software. Even if there are no huge issues with uMatrix.

**Comment by computeristic** [comment]
@unbranched you can allow/block specific elements (images/CSS/DOM/scripts...) on any domain you visit using the logger on ublock. Check [this](https://github.com/gorhill/uBlock/wiki/The-logger) page on the wiki and pay special attention to the 
'Dynamic URL filtering rules'.

**Comment by unbranched** [comment]
@computeristic Thanks, I missed that feature. That's kind of tedious though, compared to uMatrix.

**Comment by LongJohn-Silver** [comment]
> wait, is there a config syntax to make it block eg. all scripts by default? That would be awesome.

Yes, you need do block first and third party scripts if you want to block all by default, although I recommend you to only block third one since otherwise you won't be able to load any website properly, and blocking javascript by default already does that.

Screenshot from 2021-01-20 12-51-09

**Pull request merged**
