### PR TITLE
Update Javascript dependencies

### PR DESCRIPTION
**Pull request by Gusted**
## Description

Resolves: #2165 

As in issue #2165 the current version of Bootstrap still relies on jQuery, since v5 bootstrap only relies on the already existence popper.js(`@popper/core`) dependency. 
Thereby updating those 2 dependencies fixes this issue and still maintain all features.
Eventually the non beta of Bootstrap v5 can be used when it's stable.

Summary of what this PR means: 
- Update bootstrap to v5.0.0-beta1.
- Update popper.js to v2.6.0.
- Update Javascript license of popper.js.
- Bump version in `scripts.html`.

#### Check List 

- [x] I understand that by not opening an issue about a software/service/similar addition/removal, this pull request will be closed without merging.

- [x] I have read and understand [the contributing guidelines](https://github.com/privacytools/privacytools.io/blob/master/.github/CONTRIBUTING.md).

- [x] The project is [Free Libre](https://en.wikipedia.org/wiki/Free_software) and/or [Open Source](https://en.wikipedia.org/wiki/Open-source_software) Software

* Netlify preview for the mainly edited page: https://deploy-preview-2166--privacytools-io.netlify.app/

### CODE REVIEW

**Comment by dngray** [comment]
Thanks a lot for this, I'll check it out soon!

**Comment by dngray** [comment]
Looks good.

Only errors i was seeing was:

```
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.5/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.5/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/pathutil-0.16.2/lib/pathutil.rb:502: warning: Using the last argument as keyword parameters is deprecated
/usr/lib/ruby/gems/2.7.0/gems/rb-inotify-0.10.0/lib/rb-inotify/watcher.rb:66: warning: rb_safe_level will be removed in Ruby 3.0
```

I wonder if there's anything we can do about these.

**Comment by Gusted** [comment]
> Looks good.
> 
> Only errors i was seeing was:
> 
> ```
> /usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.5/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
> /usr/lib/ruby/gems/2.7.0/gems/jekyll-3.8.5/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated
> /usr/lib/ruby/gems/2.7.0/gems/pathutil-0.16.2/lib/pathutil.rb:502: warning: Using the last argument as keyword parameters is deprecated
> /usr/lib/ruby/gems/2.7.0/gems/rb-inotify-0.10.0/lib/rb-inotify/watcher.rb:66: warning: rb_safe_level will be removed in Ruby 3.0
> ```
> 
> I wonder if there's anything we can do about these.

Those are ruby dependencies. A small `sudo bundle update` should update most dependencies to 2.7+ ruby language. The only warning after updating is
```
/var/lib/gems/2.7.0/gems/pathutil-0.16.2/lib/pathutil.rb:502: warning: Using the last argument as keyword parameters is deprecated
```
Which seems to me that some dependency is still using an old version of `pathutil`, but that's an issue for another pr/issue.

**Comment by Gusted** [comment]
> ~Which seems to me that some dependency is still using an old version of `pathutil`, but that's an issue for another pr/issue.~

https://github.com/envygeeks/pathutil the last update was from 2018 and is `0.16.2` which is currently specified in `gemfile.lock`. `pathutil` is utilized by `jekyll`. 

Their is an open issue about it https://github.com/envygeeks/pathutil/issues/4 and an open PR https://github.com/envygeeks/pathutil/pull/5, however their seems to be no progress.

**Review by dngray — APPROVED** [review]

**Pull request merged**
