### PR TITLE
New email client section, thanks @freddy-m

### PR DESCRIPTION
**Pull request by dngray**
Resolves: https://github.com/privacytools/privacytools.io/pull/1990

### CODE REVIEW

**Comment by dngray** [comment]
Because you deleted your repository in https://github.com/privacytools/privacytools.io/pull/1990 I was finding I had to merge this into a branch first. There seemed to be a conflict that I've resolved.

**Comment by dngray** [comment]
Okay for some reason this didn't merge even though https://github.com/privacytools/privacytools.io/pull/1990 says it did.

**Comment by freddy-m** [comment]
Sorry @dngray, please forgive me master.

**Comment by dngray** [comment]
> Sorry @dngray, please forgive me master.

its okay, you need to approve this one though.

**Review by freddy-m — APPROVED** [review]

**Pull request merged**
