### PR TITLE
De-list/Remove Keybase

### PR DESCRIPTION
**Pull request by blacklight447-ptio**
## Description
This pull request will remove Keybase from the privacytools recommendations because of the sell out to zoom and the willingness of zoom the work with Law enforcement by knowingly not providing secure end to end encryption to free users, thereby putting  millions of peoples data at risk. see details in #1894 .

Resolves: #1894 
Closes: #1954 
Closes: #1955 

#### Check List 

- [x] I understand that by not opening an issue about a software/service/similar addition/removal, this pull request will be closed without merging.

- [x] I have read and understand [the contributing guidelines](https://github.com/privacytools/privacytools.io/blob/master/.github/CONTRIBUTING.md).

- [x] The project is [Free Libre](https://en.wikipedia.org/wiki/Free_software) and/or [Open Source](https://en.wikipedia.org/wiki/Open-source_software) Software

* Netlify preview for the mainly edited page:https://deploy-preview-1951--privacytools-io.netlify.app/software/real-time-communication/

### CODE REVIEW

**Comment by ph00lt0** [comment]
Mind that Keybase is not only listed on this page.

**Comment by subsys-R9boq8** [comment]
Please mind that Keybase presents in section "Team Chat Platforms" and Provider - Cloud Storage (may require another PR to complete).

**Comment by FreddyMarsden** [comment]
Maybe there should be a blog post about this, similar to what happened with Wire and Startpage?

**Comment by subsys-R9boq8** [comment]
> 
> 
> Maybe there should be a blog post about this, similar to what happened with Wire and Startpage?

Yes, please. Website visitors deserve to know what happened to Keybase, thus making their own decisions.

**Pull request merged**
