### PR TITLE
Replace <b> tags to <strong> and <i> tags to <em>

### PR DESCRIPTION
**Pull request by 1hiking**
## Description

This changes all b and i tags to strong and em, read the issue linked below.

Resolves: https://github.com/privacytools/privacytools.io/issues/2202

#### Check List 

- [x] I understand that by not opening an issue about a software/service/similar addition/removal, this pull request will be closed without merging.

- [x] I have read and understand [the contributing guidelines](https://github.com/privacytools/privacytools.io/blob/master/.github/CONTRIBUTING.md).

- [x] The project is [Free Libre](https://en.wikipedia.org/wiki/Free_software) and/or [Open Source](https://en.wikipedia.org/wiki/Open-source_software) Software

### CODE REVIEW

**Comment by jonaharagon** [comment]
This is, I'm sorry to say, the exact opposite of what was requested. `<strong>` and `<em>` are preferred.

**Comment by 1hiking** [comment]
Oh well... doing it ASAP.

**Comment by 1hiking** [comment]
What about now?

**Comment by rusty-snake** [comment]
Looks better, however there are still some strong->b diffs.

**Comment by 1hiking** [comment]
I think I found and replaced all of them...

**Review by rusty-snake — COMMENTED** [review]
The b->strong, i->em change looks good now. However, some merged conflicts got committed.

**Comment by 1hiking** [comment]
Fixed all of them. I apologize

**Comment by dngray** [comment]
> This is, I'm sorry to say, the exact opposite of what was requested. `<strong>` and `<em>` are preferred.

That was always my understanding.

**Pull request merged**
