### PR TITLE
Fix for tooltips on badge

### PR DESCRIPTION
**Pull request by Gusted**
## Description

Resolves: https://github.com/privacytools/privacytools.io/pull/2139#issuecomment-751338425 @dngray 

#### Check List 

- [x] I understand that by not opening an issue about a software/service/similar addition/removal, this pull request will be closed without merging.

- [x] I have read and understand [the contributing guidelines](https://github.com/privacytools/privacytools.io/blob/master/.github/CONTRIBUTING.md).

- [x] The project is [Free Libre](https://en.wikipedia.org/wiki/Free_software) and/or [Open Source](https://en.wikipedia.org/wiki/Open-source_software) Software

* Netlify preview for the mainly edited page: https://deploy-preview-2167--privacytools-io.netlify.app/

### CODE REVIEW

**Comment by dngray** [comment]
Thanks for this, will review!

**Comment by dngray** [comment]
I had a look at this, any chance we can get it not bold



Like if you look how it was originally:

**Comment by dngray** [comment]
Hmm, i think setting `font-weight: normal;` might be the right solution. Though I would have thought it would have been normal to begin with. Must have inherited the boldness from somewhere else.

**Comment by Gusted** [comment]
> Must have inherited the boldness from somewhere else.

The badge itself seems to have an `bold` font-weight.

> Hmm, i think setting `font-weight: normal;` might be the right solution.

I couldn't think of anything else.

**Review by dngray — APPROVED** [review]

**Pull request merged**
