### PR TITLE
dns: add mobileconfigs.netlify.app as iOS 14 / macOS Big Sur eDNS

### PR DESCRIPTION
**Pull request by Mikaela**
## Description

Resolves: #2059

#### Check List 

- [x] I understand that by not opening an issue about a software/service/similar addition/removal, this pull request will be closed without merging.

- [x] I have read and understand [the contributing guidelines](https://github.com/privacytools/privacytools.io/blob/master/.github/CONTRIBUTING.md).

- [x] The project is [Free Libre](https://en.wikipedia.org/wiki/Free_software) and/or [Open Source](https://en.wikipedia.org/wiki/Open-source_software) Software
  - well, kind of, the project I am adding is, while iOS 14 and macOS Big Sur aren't.

* Netlify preview for the mainly edited page: https://deploy-preview-2096--privacytools-io.netlify.app/providers/dns/#dns-ios-clients

* Code repository of the project (if applicable): https://gitlab.com/nitrohorse/ios14-encrypted-dns-mobileconfigs

### CODE REVIEW

**Comment by Mikaela** [comment]
I need guidance on how to do this PR as I don't think the Apple native support fits in cardsv2, not all providers have their own pages or profiles and I think it's better to link nitrohorse's open source website than random pseudonymous reddittor whom with I have no prior familiarity. So far AdGuard is the only one with instructions and signed profile.

**Comment by nitrohorse** [comment]
> So far AdGuard is the only one with instructions and signed profile.

NextDNS' [apple.nextdns.io](https://apple.nextdns.io) site is the only other one I know of where you can download a signed profile. And based on their instructions, looks like this new encrypted DNS support is available for Apple devices running iOS 14, iPadOS 14, tvOS 14, or macOS Big Sur.

**Comment by nitrohorse** [comment]
New vanity URL to decouple from Netlify if need be: https://encrypted-dns.party

**Comment by Mikaela** [comment]
I updated the PR, but I think I will try creating another PR with better formatting as I discussed this on Matrix and we agreed that cards don't really work in this situation and the iOS native support warrants a worth mentioning section.

**Comment by Mikaela** [comment]
Another, potentially better take on this: https://github.com/privacytools/privacytools.io/pull/2099

**Pull request closed without merging**
