### PR TITLE
Section introducing VPN breaches

### PR DESCRIPTION
**Pull request by dngray**
I think this is worthwhile, because VPN companies love to make these sorts of things hard to find, with their expensive mass advertising campaigns to control SEO.

https://deploy-preview-2010--privacytools-io.netlify.app/providers/vpn/#info

### CODE REVIEW

**Comment by FreddyMarsden** [comment]
I also feel as if The Hated One's video on [Tor vs VPN](https://yewtu.be/watch?v=6ohvf03NiIA) video has a place in that section seeing as we're editing this page. Otherwise LGTM!

**Comment by dngray** [comment]
> I also feel as if The Hated One's video on [Tor vs VPN](https://yewtu.be/watch?v=6ohvf03NiIA) video has a place in that section seeing as we're editing this page. Otherwise LGTM!

we could perhaps do what we did with the other VPN video and put it below that one? I did watch that video and thought it was pretty accurate.

**Comment by FreddyMarsden** [comment]
@dngray yes, that was what I meant, because I don't think it has anything to do with breaches really.

**Comment by dngray** [comment]
> @dngray yes, that was what I meant, because I don't think it has anything to do with breaches really. Puting it next to the Tom Scott video is were it should be.

ah yeah I thought that's what you meant. See https://github.com/privacytools/privacytools.io/pull/2011

**Review by jonaharagon — APPROVED** [review]

**Review by freddy-m — APPROVED** [review]

**Pull request merged**
